---
- name: Stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

- name: Disable services
  systemd:
    name: "{{ item }}"
    enabled: no
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

- name: Remove unwanted packages before upgrading
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
    - nginx

- name: Copy tweaked hotplug.d service script
  copy:
    src: "{{item}}"
    dest: /etc/hotplug.d/iface/{{item}}
  with_items:
    - 20-firewall
    - 25-dnsmasq

- name: Remove unwanted files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
   - /etc/nginx/
   # - /lib/systemd/system/ubus.service
   - /lib/systemd/system/contenthub-usb.service
   # - /lib/systemd/system/ubox.service
   - /lib/systemd/system/uhttpd.service
   - /lib/systemd/system/rabbitmq-server.service
   # - /etc/hotplug.d/iface/25-dnsmasq
   - /etc/django-fastcgi
   # - nginx.conf
   # - nginx.default
   - /srv/
   - /etc/udev/rules.d/81-modem.rules
   - /etc/udev/rules.d/80-uploaded.rules
   - /etc/hotplug.d/iface/90-ar2f
   - /var/log/celery/
   - /var/log/fsck/
   - /var/log/installer/
   - /var/log/nginx/
   - /var/log/rabbitmq/
   - /var/log/samba/
