- name: Pull Nginx from repository and start it
  docker_container:
    docker_host: unix://var/run/balena-engine.sock
    name: nginx
    image: kajou/nginx-i386:latest
    published_ports: 8000:80
    restart_policy: always
    state: started
    pull: yes
    labels: traefik.frontend.rule=Host:"{{project_type}}"
    volumes:
      - "{{kajou_website_path}}:/kajou-website"
      - /media/hdd/config-files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /media/hdd/config-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx/:/var/log/nginx/
  tags:
    - pull_container
